<?php
define('ONSCROLL_URL', 'http://cdn.onscroll.com/onscroll.ms.js');

/**
 * Variable defaults.
 */
function _onscroll_variable_defaults() {
  return array(
    'onscroll_url' => ONSCROLL_URL,
    'onscroll_enabled' => FALSE,
    'onscroll_ad_slot' => 'custom',
    'onscroll_margin' => 600,
    'onscroll_margin_top' => 10,
    'onscroll_mode' => 'sticky',
    'onscroll_height' => 250,
    'onscroll_width' => 300,
    'onscroll_reload' => FALSE,
    'onscroll_interval' => 30,
    'onscroll_campaign_id' => '',
    'onscroll_creative_id' => '',
    'onscroll_account_id' => '',
    'onscroll_code' => '',
  );
}

/**
 * Get variable.
 * 
 * @param $name
 */
function _onscroll_variable_get($name) {
  $defaults = _onscroll_variable_defaults();
  $default = isset($defaults[$name]) ? $defaults[$name] : NULL;
  return variable_get($name, $default);
}

/**
 * Implements hook_permission().
 */
function onscroll_permission() {
  return array(
    'administer onscroll' => array(
      'title' => t('Administer onscroll'),
      'description' => t('Administer account settings and visibility of onscroll on your site.'),
    ),
  );
}

/**
 * Implements hook_js_alter().
 */
function onscroll_js_alter(&$javascript) {
  // Remove the OnScroll ad slot.
  // This is included in the base64 encoded onscroll script.
  foreach ($javascript as $key => $value) {
    if (isset($value['data'])) {
      if (strstr($value['data'], 'googletag.slots') && strstr($value['data'], _onscroll_variable_get('onscroll_ad_slot'))) {
        unset($javascript[$key]);
      }
    }
  }
}

/**
 * Implements hook_preprocess_html().
 */
function onscroll_preprocess_html(&$variables) {
  _onscroll_add_script();
}

/**
 * Implements hook_menu().
 */
function onscroll_menu() {
  $items['admin/config/system/onscroll'] = array(
    'title' => 'OnScroll',
    'description' => 'Configure onscroll blocks on your website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('onscroll_admin_settings_form'),
    'access arguments' => array('administer onscroll'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_help().
 */
function onscroll_help($path, $arg) {
  switch ($path) {
    case 'admin/config/system/onscroll':
      return t('<a href="@url">OnScroll</a> determines the most appropriate time to deliver a viewable ad based on user behaviour.', array('@url' => 'http://www.onscroll.com/'));
  }
}

/**
 * Get the onscroll block content.
 */
function _onscroll_add_script() {
  $onscroll_content = array();
  if (!path_is_admin(current_path())) {
    if (_onscroll_variable_get('onscroll_enabled')) {
      // Add inline script.
      $ad_slot = '';
      if (_onscroll_variable_get('onscroll_ad_slot') == 'custom') {
        $ad_slot = _onscroll_variable_get('onscroll_code');
      }
      else {
        if (module_exists('dfp')) {
          // Render the tag first so that the JS is available in drupal_add_js().
          $tag = dfp_tag(_onscroll_variable_get('onscroll_ad_slot'));
          $rendered_tag = render($tag);

          $ad_slot .= '<script type="text/javascript" src="http://www.googletagservices.com/tag/js/gpt.js"></script>' . PHP_EOL;

          foreach (drupal_add_js() as $key => $value) {
            if (is_numeric($key)) {
              if (strstr($value['data'], 'googletag')) {
                if (strstr($value['data'], 'googletag.slots')) {
                  if (strstr($value['data'], _onscroll_variable_get('onscroll_ad_slot'))) {
                    $ad_slot .= '<script type="text/javascript">' . $value['data'] . '</script>' . PHP_EOL;
                  }
                }
                else {
                  $ad_slot .= '<script type="text/javascript">' . $value['data'] . '</script>' . PHP_EOL;
                }
              }
            }
          }
          $ad_slot .= $rendered_tag;
        }
      }

      // Add onscroll configuration.
      $script = 'var onScrOll=new Object();' . PHP_EOL;
      $script .= 'onScrOll.placeholder="onscroll-container";' . PHP_EOL;
      $script .= 'onScrOll.code="' . base64_encode($ad_slot) . '";' . PHP_EOL;
      $script .= 'onScrOll.margin=' . _onscroll_variable_get('onscroll_margin') . ';' . PHP_EOL;
      $script .= 'onScrOll.marginTop=' . _onscroll_variable_get('onscroll_margin_top') . ';' . PHP_EOL;
      $script .= 'onScrOll.mode="' . _onscroll_variable_get('onscroll_mode') . '";' . PHP_EOL;
      $script .= 'onScrOll.height=' . _onscroll_variable_get('onscroll_height') . ';' . PHP_EOL;
      $script .= 'onScrOll.width=' . _onscroll_variable_get('onscroll_width') . ';' . PHP_EOL;
      $script .= 'onScrOll.reload=' . ((_onscroll_variable_get('onscroll_reload') == FALSE) ? 'false' : 'true') . ';' . PHP_EOL;
      drupal_add_js($script, array('scope' => 'footer', 'type' => 'inline'));

      // Add external script.
      $script = _onscroll_variable_get('onscroll_url');
      $script .= '?campaignId=' . _onscroll_variable_get('onscroll_campaign_id');
      $script .= '&creativeId=' . _onscroll_variable_get('onscroll_creative_id');
      $script .= '&accountId=' . _onscroll_variable_get('onscroll_account_id');
      drupal_add_js($script, array('scope' => 'footer', 'type' => 'external'));
    }
  }
}

/**
 * Implements hook_block_info().
 */
function onscroll_block_info() {
  $blocks['onscroll'] = array(
    'info' => t('OnScroll'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
* Implements hook_block_view().
*/
function onscroll_block_view($delta = '') {
  $block = array();

  switch ($delta) {
    case 'onscroll':
      // Block to position the onscroll ad.
      $block['content'] ='<div id="onscroll-container"></div>';
      break;
  }

  return $block;
}
