<?php
define('ONSCROLL_URL', 'http://cdn.onscroll.com/onscroll.ms.js');

/**
 * Implements hook_permission().
 */
function onscroll_permission() {
  return array(
    'administer onscroll' => array(
      'title' => t('Administer onscroll'),
      'description' => t('Administer account settings and visibility of onscroll on your site.'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function onscroll_menu() {
  $items['admin/config/system/onscroll'] = array(
    'title' => 'OnScroll',
    'description' => 'Configure onscroll blocks on your website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('onscroll_admin_settings_form'),
    'access arguments' => array('administer onscroll'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'admin.inc',
  );

  return $items;
}

/**
 * Implementation of hook_help().
 */
function onscroll_help($path, $arg) {
  switch ($path) {
    case 'admin/config/system/onscroll':
      return t('<a href="@url">OnScroll</a> determines the most appropriate time to deliver a viewable ad based on user behaviour.', array('@url' => 'http://www.onscroll.com/'));
  }
}

/**
 * Implements preprocess_html().
 */
function onscroll_preprocess_html($variables) {
  if (!path_is_admin(current_path())) {
    if (variable_get('onscroll_enabled')) {
      // Add inline script.
      debug("1");
      $ad_slot = '';
      if (variable_get('onscroll_ad_slot', 'custom') == 'custom') {
        $ad_slot = variable_get('onscroll_code');
      }
      else {
        if (module_exists('dfp')) {
          $ad_slot .= '<script type="text/javascript" src="http://www.googletagservices.com/tag/js/gpt.js"></script>' . PHP_EOL;

          foreach (drupal_add_js() as $key => $value) {
            if (is_numeric($key)) {
              if (strpos($value['data'], 'googletag') !== FALSE) {
                if (strpos($value['data'], 'googletag.slots') !== FALSE) {
                  //@todo grab the actual themed machine name
                  if (strpos($value['data'], variable_get('onscroll_ad_slot')) !== FALSE) {
                    $ad_slot .= $value['data'] . PHP_EOL;
                  }
                }
                else {
                  $ad_slot .= $value['data'] . PHP_EOL;
                }
              }
            }
          }
//          krumo(drupal_add_js(NULL, $options), drupal_get_js());
          $ad_slot .= render(dfp_tag(variable_get('onscroll_ad_slot')));
          /*
                    $ad_slot .= '

                            <script type="text/javascript">
                                            googletag.defineSlot("/359/autoexpress.co.uk", [[300, 250], [300, 600]], "dfp-ad-mpu_2")
                                              .addService(googletag.pubads())
                                              .setTargeting("position", "2");
                            </script>

                            <script type="text/javascript">
                                            googletag.cmd.push(function() {
                                              googletag.pubads().enableAsyncRendering();
                                              googletag.pubads().enableSingleRequest();
                                              googletag.pubads().collapseEmptyDivs();
                                              googletag.pubads().setTargeting("zone", "homepage");
                                              googletag.pubads().setTargeting("live", "yes");
                                              googletag.pubads().setTargeting("ord", "8335801736");
                                            });
                                            googletag.enableServices();
                            </script>

                            <div id="dfp-ad-mpu_2" class="dfp-tag-wrapper">
                                            <script type="text/javascript">
                                                                googletag.cmd.push(function() {
                                                                                            googletag.display("dfp-ad-mpu_2");
                                                                });
                                                            </script>
                            </div>';
          */
        }
      }

      $script = 'var onScrOll=new Object();' . PHP_EOL;
      $script .= 'onScrOll.code="' . base64_encode($ad_slot) . '";' . PHP_EOL;
      $script .= 'onScrOll.margin=' . variable_get('onscroll_margin', 600) . ';' . PHP_EOL;
      $script .= 'onScrOll.marginTop=' . variable_get('onscroll_margin_top', 10) . ';' . PHP_EOL;
      $script .= 'onScrOll.mode="' . variable_get('onscroll_mode', 'sticky') . '";' . PHP_EOL;
      $script .= 'onScrOll.height=' . variable_get('onscroll_height', 250) . ';' . PHP_EOL;
      $script .= 'onScrOll.width=' . variable_get('onscroll_width', 300) . ';' . PHP_EOL;
      $script .= 'onScrOll.reload=' . ((variable_get('onscroll_reload', FALSE) == FALSE) ? 'false' : 'true') . ';' . PHP_EOL;
      echo '<pre>';
      print_r($ad_slot);
      drupal_add_js($script, array('scope' => 'footer', 'type' => 'inline'));

      // Add external script.
      $script = variable_get('onscroll_url', ONSCROLL_URL);
      $script .= '?campaignId=' . variable_get('onscroll_campaign_id');
      $script .= '&creativeId=' . variable_get('onscroll_creative_id');
      $script .= '&accountId=' . variable_get('onscroll_account_id');
      drupal_add_js($script, array('scope' => 'footer', 'type' => 'external'));
    }
  }
}
